# Generated by Django 4.1.1 on 2022-09-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=12)),
                ('date_of_bith', models.DateField()),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
