# Generated by Django 4.1.1 on 2022-09-22 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LES1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='date_of_bith',
            new_name='date_of_birth',
        ),
    ]
