# Generated by Django 4.1.1 on 2022-09-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LES1', '0002_rename_date_of_bith_userdata_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='re_password',
            field=models.CharField(default='Konda@74', max_length=12),
        ),
    ]
