# Generated by Django 4.1.1 on 2022-09-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LES1', '0003_userdata_re_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='re_password',
            field=models.CharField(max_length=12),
        ),
    ]
